# Startup
exec-once = waybar
# exec-once = quickshell

# notifs
exec-once = mako --max-history 50

exec-once = swww-daemon

exec-once = copyq

exec-once = rog-control-center

# idle management (direct process, not systemd)
exec-once = ~/.config/hypr/scripts/idle.sh start

# wallpaper utils
exec-once = wallutils & waypaper --restore & wal -R -n
