foreground         #C5C9C7
background         #090E13
background_opacity 1.0
cursor             #f2f1ef

active_tab_foreground     #090E13
active_tab_background     #C5C9C7
inactive_tab_foreground   #C5C9C7
inactive_tab_background   #090E13

active_border_color   #C5C9C7
inactive_border_color #090E13
bell_border_color     #c4746e

color0       #090E13
color8       #909398
color1       #c4746e
color9       #E46876
color2       #8a9a7b
color10      #87a987
color3       #c4b28a
color11      #E6C384
color4       #8ba4b0
color12      #7FB4CA
color5       #a292a3
color13      #938AA9
color6       #8ea4a2
color14      #7AA89F
color7       #A4A7A4
color15      #C5C9C7
