# Kanso Zen Hyprland Colors

# Variables expected by configuration.conf
$activeBorder = rgba(8ea4a2ff) rgba(8ba4b0ff) 45deg
$inactiveBorder = rgba(1C1E25ff)

# Standard colors
$backgroundCol = 0xff090E13
$foregroundCol = 0xffC5C9C7
$cursor = 0xfff2f1ef

$color0 = 0xff090E13
$color1 = 0xffc4746e
$color2 = 0xff8a9a7b
$color3 = 0xffc4b28a
$color4 = 0xff8ba4b0
$color5 = 0xffa292a3
$color6 = 0xff8ea4a2
$color7 = 0xffA4A7A4
$color8 = 0xff909398
$color9 = 0xffE46876
$color10 = 0xff87a987
$color11 = 0xffE6C384
$color12 = 0xff7FB4CA
$color13 = 0xff938AA9
$color14 = 0xff7AA89F
$color15 = 0xffC5C9C7
